/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.*;

/**
 *
 * @author user
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
        txtnumerador1.requestFocusInWindow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtnumerador1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txtdenominador1 = new javax.swing.JTextField();
        cmboperaciones = new javax.swing.JComboBox<>();
        txtnumerador2 = new javax.swing.JTextField();
        txtdenominador2 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txtnumerador3 = new javax.swing.JTextField();
        txtdenominador3 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        cmdcalcular = new javax.swing.JButton();
        cmdlimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("OPERACIONES CON FRACCIONARIOS Y MIXTO");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 10, 270, 30));
        jPanel2.add(txtnumerador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 90, 30));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 90, 10));
        jPanel2.add(txtdenominador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 90, 30));

        cmboperaciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Suma", "Resta", "Multiplicación", "División", " " }));
        jPanel2.add(cmboperaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 110, 30));
        jPanel2.add(txtnumerador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 90, 30));
        jPanel2.add(txtdenominador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 90, 30));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 90, 10));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("=");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 20, 20));
        jPanel2.add(txtnumerador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 90, 30));
        jPanel2.add(txtdenominador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 90, 30));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 90, 10));

        cmdcalcular.setText("Calcular");
        cmdcalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdcalcularActionPerformed(evt);
            }
        });
        jPanel2.add(cmdcalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 173, 80, 30));

        cmdlimpiar.setText("Limpiar");
        cmdlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdlimpiarActionPerformed(evt);
            }
        });
        jPanel2.add(cmdlimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 173, 80, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 510, 370));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdcalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdcalcularActionPerformed
         int op,num, num2, num3, den, den2, den3;
         Fraccionario f1, f2, f3=null;
         
         op = cmboperaciones.getSelectedIndex();
         num = Integer.parseInt(txtnumerador1.getText());
         num2 = Integer.parseInt(txtnumerador2.getText());
         den = Integer.parseInt(txtdenominador1.getText());
         den2 = Integer.parseInt(txtdenominador2.getText());
         
         
         f1= new Fraccionario(num, den);
         f2= new Fraccionario(num2, den2);
         
         switch(op){
             case 0: 
                 f3 = f1.sumar(f2);
                 break;
             case 1:
                 f3 = f1.restar(f2);
                 break;
             case 2: 
                 f3 = f1.multiplicar(f2);
                 break;
             case 3:
                 f3 = f1.dividir(f2);
                 break;
         }
         txtnumerador3.setText(""+ f3.getNumerador());
         txtdenominador3.setText("" + f3.getDenominador());
    }//GEN-LAST:event_cmdcalcularActionPerformed

    private void cmdlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdlimpiarActionPerformed
      txtnumerador1.setText("");
      txtnumerador2.setText("");
      txtnumerador3.setText("");
      txtdenominador1.setText("");
      txtdenominador2.setText("");
      txtdenominador3.setText("");
      txtnumerador1.requestFocusInWindow();
      
    }//GEN-LAST:event_cmdlimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmboperaciones;
    private javax.swing.JButton cmdcalcular;
    private javax.swing.JButton cmdlimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField txtdenominador1;
    private javax.swing.JTextField txtdenominador2;
    private javax.swing.JTextField txtdenominador3;
    private javax.swing.JTextField txtnumerador1;
    private javax.swing.JTextField txtnumerador2;
    private javax.swing.JTextField txtnumerador3;
    // End of variables declaration//GEN-END:variables
}
